### ISSUE TITLE
Method for determining which app is responsible for CAP

### ISSUE THREAD

**Issue by tombull** [russss/python-emv#10]
In card.py, you note:

```
# We're selecting the last app on the card here, which on Barclays
# cards seems to always be the Barclays one.
#
# It would be good to work out what logic to use to work out
# which app is responsible for CAP.
```

From my research, you can just select the app with ADF `[A0 00 00 00 03 80 02]` which will always be the bank-specific app, i.e. the one responsible for CAP.

**Comment by tombull** [comment]
Note: the app with ADF `[A0 00 00 00 03 80 02]` happens to be the last app listed on every card I've tested - so the code as it stands works fine for the cards that I can get access to.

**Comment by russss** [comment]
Thanks! I've just updated the comment for the moment in case this ever becomes an issue.
