### ISSUE TITLE
 Processing Options Data Object List (PDOL) - last 2 bytes are missing.

### ISSUE THREAD

**Issue by przemobe** [russss/python-emv#22]
Hello,

I have started using the project with contactless cards.
I found an issue when processing Select Application Response:
6f:33:84:07:a0:00:00:00:03:20:10:a5:28:50:09:56:49:53:41:20:43:41:52:44:9f:38:1a:9f:66:04:9f:02:06:9f:03:06:9f:1a:02:95:05:5f:2a:02:9a:03:9c:01:9f:37:04:9a:03:90:00

It is decoded like this:

<SuccessResponse: "Process completed", data: {
(6F) FCI Template: {
(84) Dedicated File (DF) Name: [A0 00 00 00 03 20 10], 
(A5) FCI Proprietary Template: {
(50) Application Label: "VISA CARD", 
([9F 38]) Processing Options Data Object List (PDOL): DOL([([9F 66], 4), (([9F 02]) Amount, Authorised, 6), (([9F 03]) Amount, Other (Numeric), 6), (([9F 1A]) Terminal Country Code, 2), ((95) Terminal Verification Results, 5), (([5F 2A]) Transaction Country Code, 2), ((9A) Transaction Date, 3), ((9C) Transaction Type, 1), (([9F 37]) Unpredictable Number, 4)])}}}>

However when I decode the respose with other tool the PDOL is like this:
9F66049F02069F03069F1A0295055F2A029A039C019F37049A03

So it looks like python-emv is missing last 2 bytes : last tag(9A) indicating length 03.

Would you please check this?

Best Regards,
Przemobe

**Comment by russss** [comment]
Thanks for the report! It looks like this is because the 0x9A tag is present twice in the DOL, which I assumed wouldn't happen. I have no idea why this is done but I've changed the library to allow this now. I may not release a new version immediately but I'll push the changes to git.
