### ISSUE TITLE
Unable to fetch card data

### ISSUE THREAD

**Issue by Manouchehri** [russss/python-emv#4]
On nearly all my cards I'm getting `Unable to fetch card data: <ErrorResponse: "Referenced data (data objects) not found">` after `Fetching card data...`.

All the cards I've tested are issued in Canada. Cards _without_ MasterCard or Visa (credit) seem to work. e.g. Visa Debit and Interac work fine.

Seems to be similar to #3. Any ideas?

Thanks!

**Comment by russss** [comment]
Sorry, it looks like I wasn't getting notifications for this repository...

Can you grab the full error output with the `-l debug` flag? Given the point it's failing at, it's unlikely it'll contain any sensitive info but it's obviously at your own risk!

**Comment by igorva** [comment]
Hi,
I got the same problem: the tool works with Visa Debit, but fails with MasterCard. Output:

INFO:emv.transmission:Connected to reader
DEBUG:emv.transmission:Tx: [00 A4 04 00 0E 31 50 41 59 2E 53 59 53 2E 44 44 46 30 31 00]
DEBUG:emv.transmission:Rx: [], SW1: 61, SW2: 2c
DEBUG:emv.transmission:Tx: [00 C0 00 00 2C]
DEBUG:emv.transmission:Rx: [6F 2A 84 0E 31 50 41 59 2E 53 59 53 2E 44 44 46 30 31 A5 18 88 01 01 5F 2D 06 66 69 73 76 65 6E 9F 11 01 01 BF 0C 05 DF 02 02 02 46], SW1: 90, SW2: 00
DEBUG:emv.transmission:Tx: [00 B2 01 0C 00]
DEBUG:emv.transmission:Rx: [], SW1: 6c, SW2: 2b
DEBUG:emv.transmission:Tx: [00 B2 01 0C 2B]
DEBUG:emv.transmission:Rx: [70 29 61 27 4F 09 A0 00 00 00 04 10 10 AA 01 50 0A 4D 61 73 74 65 72 43 61 72 64 9F 12 0A 4D 61 73 74 65 72 43 61 72 64 87 01 01], SW1: 90, SW2: 00
Available apps: "MasterCard"

Application "MasterCard", DF Name: [A0 00 00 00 04 10 10 AA 01]
DEBUG:emv.transmission:Tx: [00 A4 04 00 09 A0 00 00 00 04 10 10 AA 01 00]
DEBUG:emv.transmission:Rx: [], SW1: 61, SW2: 45
DEBUG:emv.transmission:Tx: [00 C0 00 00 45]
DEBUG:emv.transmission:Rx: [6F 43 84 09 A0 00 00 00 04 10 10 AA 01 A5 36 50 0A 4D 61 73 74 65 72 43 61 72 64 87 01 01 5F 2D 06 66 69 73 76 65 6E 9F 11 01 01 9F 12 0A 4D 61 73 74 65 72 43 61 72 64 BF 0C 0A 9F 6E 07 02 46 00 00 30 30 00], SW1: 90, SW2: 00
┌FCI Proprietary Data──────────────────────┬────────────────────────────────────┐
│ Tag     │ Name                           │ Value                              │
├─────────┼────────────────────────────────┼────────────────────────────────────┤
│ [BF 0C] │ FCI Issuer Discretionary Data  │ { [9F 6E]: [02 46 00 00 30 30 00]} │
│ [9F 12] │ Application Preferred Name     │ "MasterCard"                       │
│ [87]    │ Application Priority Indicator │ 1                                  │
│ [9F 11] │ Issuer Code Table Index        │ [01]                               │
│ [50]    │ Application Label              │ "MasterCard"                       │
│ [5F 2D] │ Language Preference            │ "fisven"                           │
└─────────┴────────────────────────────────┴────────────────────────────────────┘
DEBUG:emv.transmission:Tx: [00 B2 01 0C 00]
DEBUG:emv.transmission:Rx: [], SW1: 6a, SW2: 82

Fetching card data...
DEBUG:emv.transmission:Tx: [80 CA 9F 17 00]
DEBUG:emv.transmission:Rx: [], SW1: 6c, SW2: 04
DEBUG:emv.transmission:Tx: [80 CA 9F 17 04]
DEBUG:emv.transmission:Rx: [9F 17 01 05], SW1: 90, SW2: 00
DEBUG:emv.transmission:Tx: [80 CA 9F 36 00]
DEBUG:emv.transmission:Rx: [], SW1: 6a, SW2: 88
Unable to fetch card data: <ErrorResponse: "Referenced data (data objects) not found">

**Comment by silverhigh1** [comment]
brothers add me on icq and we can do serious business have data tools and method the obstacle must make way fr the objective.720922345

**Comment by russss** [comment]
Sorry I never got to this. This error is "normal" for mastercard but I've updated `emvtool info` so that it ignores it now.
