### ISSUE TITLE
Will this work as a basic RFID access?

### ISSUE THREAD

**Issue by amunizp** [russss/python-emv#5]
Could this be used not to extract payment but just to identify cards like Oyster and other hotelroom type cards?

**Comment by russss** [comment]
This library doesn't currently support RFID and focuses on payment cards at the moment. If you want to play with RFID then [RFIDIOt](https://github.com/AdamLaurie/RFIDIOt) is one library to do it (as used by LHS's [doorbot](https://github.com/londonhackspace/Doorbot/blob/master/doorbot.py)).
