### ISSUE TITLE
Apps are stored on some cards differently to how Barclays stores apps

### ISSUE THREAD

**Issue by tombull** [russss/python-emv#9]
For some cards (I've tested one like this from the Co-Operative Bank), the different apps are stored in different records rather than all in the one value. To get an accurate list of apps on a Co-Op card, you need to do something like:

```
def list_applications(self):
    res = self.tp.exchange(SelectCommand('1PAY.SYS.DDF01'))
    sfi = res.data[Tag.FCI][Tag.FCI_PROP][Tag.SFI][0]
    apps = []
    for i in range(1, 31):
        try:
            res = self.tp.exchange(ReadCommand(i, sfi))
        except:
            break
        new_apps = res.data[Tag.RECORD][Tag.APP]
        if type(new_apps) is not list:
            new_apps = [new_apps]
        apps.extend(new_apps)
    return apps
```

This isn't written well or with comments, which is why I've not submitted a pull request.

**Comment by tombull** [comment]
Note: The code I've written is also compatible with Barclays cards.

**Comment by russss** [comment]
Thanks for the info - I've made that change although it doesn't appear to affect any the cards I have. I wonder why the co-op card does that...
